from __future__ import annotations

from app.agents.base import OrganelleCard


ORGANELLE_CARDS: dict[str, OrganelleCard] = {
    "nucleus": OrganelleCard(
        type="nucleus",
        name="Nucleus",
        role="Genome manager, transcription planner, and cell-cycle checkpoint controller",
        biological_scope=["transcription", "DNA replication", "DNA repair", "cell-cycle gating"],
        can_do=["transcribe_gene", "export_mrna", "replicate_dna", "repair_dna", "advance_cell_cycle", "send_signal"],
        cannot_do=["translate proteins", "produce ATP"],
        consumes=["ATP", "nucleotides"],
        produces=["mRNA", "cell-cycle signals"],
        depends_on=["mitochondrion", "ribosome", "rough_er", "golgi", "centrosome"],
        communicates_with=["ribosome", "mitochondrion", "centrosome", "cytoskeleton"],
        failure_modes=["DNA damage", "checkpoint failure", "low ATP"],
    ),
    "nucleolus": OrganelleCard(
        type="nucleolus",
        name="Nucleolus",
        role="Ribosome subunit production coordinator",
        biological_scope=["ribosome capacity support"],
        can_do=["send_signal", "request_resource", "explain_state"],
        cannot_do=["translate proteins", "run the cell cycle"],
        consumes=["ATP", "nucleotides", "amino acids"],
        produces=["ribosome support signals"],
        depends_on=["nucleus", "mitochondrion"],
        communicates_with=["ribosome", "nucleus"],
        failure_modes=["stress", "resource shortage"],
    ),
    "ribosome": OrganelleCard(
        type="ribosome",
        name="Ribosome",
        role="Protein synthesis from mRNA",
        biological_scope=["translation", "protein output"],
        can_do=["translate_mrna", "request_resource", "send_signal"],
        cannot_do=["replicate DNA", "package Golgi cargo"],
        consumes=["mRNA", "amino acids", "ATP"],
        produces=["proteins", "secretory cargo"],
        depends_on=["nucleus", "plasma_membrane", "mitochondrion"],
        communicates_with=["nucleus", "rough_er", "plasma_membrane"],
        failure_modes=["low amino acids", "low ATP", "mRNA starvation"],
    ),
    "rough_er": OrganelleCard(
        type="rough_er",
        name="Rough ER",
        role="Folding, quality control, and early protein processing",
        biological_scope=["protein folding", "quality control", "Golgi handoff"],
        can_do=["fold_protein", "package_cargo", "send_signal", "request_resource"],
        cannot_do=["translate mRNA", "produce ATP"],
        consumes=["unfolded proteins", "ATP"],
        produces=["folded proteins", "Golgi cargo"],
        depends_on=["ribosome", "mitochondrion", "golgi"],
        communicates_with=["ribosome", "golgi", "nucleus"],
        failure_modes=["ER stress", "misfolded cargo"],
    ),
    "smooth_er": OrganelleCard(
        type="smooth_er",
        name="Smooth ER",
        role="Lipid synthesis and calcium buffering",
        biological_scope=["lipid support", "stress moderation", "calcium regulation"],
        can_do=["reduce_stress", "request_resource", "send_signal"],
        cannot_do=["translate mRNA", "package vesicles"],
        consumes=["ATP", "lipid precursors"],
        produces=["lipids", "stress buffering"],
        depends_on=["mitochondrion", "plasma_membrane"],
        communicates_with=["plasma_membrane", "nucleus"],
        failure_modes=["low ATP", "lipid shortage"],
    ),
    "golgi": OrganelleCard(
        type="golgi",
        name="Golgi Body",
        role="Cargo modification, sorting, and vesicle dispatch",
        biological_scope=["cargo packaging", "vesicle routing"],
        can_do=["package_cargo", "dispatch_vesicle", "send_signal"],
        cannot_do=["translate mRNA", "replicate DNA"],
        consumes=["folded cargo", "ATP"],
        produces=["vesicle jobs", "secretory cargo", "membrane proteins"],
        depends_on=["rough_er", "cytoskeleton", "mitochondrion"],
        communicates_with=["rough_er", "cytoskeleton", "plasma_membrane", "lysosome"],
        failure_modes=["trafficking backlog", "low transport capacity"],
    ),
    "mitochondrion": OrganelleCard(
        type="mitochondrion",
        name="Mitochondrion",
        role="ATP production and metabolic stress management",
        biological_scope=["ATP generation", "resource requests", "ROS handling"],
        can_do=["produce_atp", "reduce_stress", "request_resource", "send_signal"],
        cannot_do=["transcribe genes", "package Golgi cargo"],
        consumes=["glucose", "oxygen", "ADP"],
        produces=["ATP", "ROS"],
        depends_on=["plasma_membrane", "peroxisome"],
        communicates_with=["plasma_membrane", "peroxisome", "nucleus"],
        failure_modes=["low oxygen", "low glucose", "high ROS"],
    ),
    "plasma_membrane": OrganelleCard(
        type="plasma_membrane",
        name="Plasma Membrane",
        role="Selective transport and boundary sensing",
        biological_scope=["resource import", "waste export", "environment sensing"],
        can_do=["import_resource", "export_waste", "send_signal", "reduce_stress"],
        cannot_do=["replicate DNA", "translate proteins"],
        consumes=["ATP"],
        produces=["imported nutrients", "exported waste"],
        depends_on=["mitochondrion"],
        communicates_with=["mitochondrion", "cytoplasm", "nucleus"],
        failure_modes=["membrane damage", "leakiness", "transport bottlenecks"],
    ),
    "cytoplasm": OrganelleCard(
        type="cytoplasm",
        name="Cytoplasm",
        role="Shared medium for resource balancing and signal routing",
        biological_scope=["resource balancing", "signal routing"],
        can_do=["move_cargo", "send_signal", "explain_state"],
        cannot_do=["replicate DNA", "translate proteins"],
        consumes=["ATP"],
        produces=["balanced transport"],
        depends_on=["plasma_membrane", "cytoskeleton"],
        communicates_with=[
            "nucleus",
            "ribosome",
            "rough_er",
            "smooth_er",
            "golgi",
            "mitochondrion",
            "plasma_membrane",
            "cytoskeleton",
            "lysosome",
            "endosome",
            "peroxisome",
            "centrosome",
        ],
        failure_modes=["diffusion bottlenecks"],
    ),
    "cytoskeleton": OrganelleCard(
        type="cytoskeleton",
        name="Cytoskeleton",
        role="Intracellular transport and spindle preparation",
        biological_scope=["cargo movement", "mitotic support"],
        can_do=["move_cargo", "prepare_spindle", "send_signal"],
        cannot_do=["produce ATP", "transcribe genes"],
        consumes=["ATP"],
        produces=["transport progress", "spindle readiness"],
        depends_on=["golgi", "centrosome", "mitochondrion"],
        communicates_with=["golgi", "centrosome", "plasma_membrane"],
        failure_modes=["transport slowdown", "spindle defects"],
    ),
    "lysosome": OrganelleCard(
        type="lysosome",
        name="Lysosome",
        role="Waste degradation and recycling",
        biological_scope=["waste recycling", "stress cleanup"],
        can_do=["recycle_waste", "reduce_stress", "send_signal"],
        cannot_do=["replicate DNA", "translate proteins"],
        consumes=["waste", "damaged components", "ATP"],
        produces=["amino acids", "lipids"],
        depends_on=["golgi", "mitochondrion"],
        communicates_with=["golgi", "peroxisome", "nucleus"],
        failure_modes=["overload", "acidification failure"],
    ),
    "endosome": OrganelleCard(
        type="endosome",
        name="Endosome",
        role="Sorting internalized cargo",
        biological_scope=["cargo routing", "recycling handoff"],
        can_do=["dispatch_vesicle", "recycle_waste", "send_signal"],
        cannot_do=["replicate DNA", "translate proteins"],
        consumes=["incoming cargo"],
        produces=["recycling signals"],
        depends_on=["plasma_membrane", "lysosome"],
        communicates_with=["plasma_membrane", "lysosome"],
        failure_modes=["sorting backlog"],
    ),
    "peroxisome": OrganelleCard(
        type="peroxisome",
        name="Peroxisome",
        role="Oxidative stress moderation and lipid handling",
        biological_scope=["ROS cleanup", "fatty-acid handling"],
        can_do=["reduce_stress", "request_resource", "send_signal"],
        cannot_do=["translate proteins", "advance cell cycle"],
        consumes=["lipids", "ROS"],
        produces=["reduced oxidative stress"],
        depends_on=["mitochondrion", "lysosome"],
        communicates_with=["mitochondrion", "lysosome"],
        failure_modes=["oxidative overload"],
    ),
    "centrosome": OrganelleCard(
        type="centrosome",
        name="Centrosome",
        role="Microtubule organization and spindle coordination",
        biological_scope=["spindle coordination", "mitotic readiness"],
        can_do=["prepare_spindle", "send_signal"],
        cannot_do=["translate proteins", "produce ATP"],
        consumes=["ATP"],
        produces=["spindle readiness"],
        depends_on=["cytoskeleton", "mitochondrion", "nucleus"],
        communicates_with=["cytoskeleton", "nucleus"],
        failure_modes=["spindle checkpoint failure"],
    ),
}


def get_organelle_card(organelle_type: str) -> OrganelleCard:
    return ORGANELLE_CARDS[organelle_type]
